# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/122IglCmKUEogzFt4wGWm4ebBj03T5VeZ

2. Discounting Computation Assignment:
"""

from datetime import date
try:
  FV = int(input("How much money you need after 60 years ?"))
  yearofmaturity = 60 

  currentAge = int(input("What is your current Age?"))
  year = yearofmaturity - currentAge
  rateofInterest =  float(input("Interest rate?"))
  rate = rateofInterest /100 


  today = date.today()
  d1 = today.strftime("%m-%d-%Y")



 
  PV = FV / ((1+ rate)**year) 

  
except Exception as error:
  print("An exception was thrown!")
  print(str(error))
  
  
print("Amount Needed in 60 years         :" ,"{:,}".format(FV))

print("Rate of interest                  :" ,"{:.2f}".format(rateofInterest))

print("Today's Date                      :" ,d1 )

print("Amount to be invested today       :" ,"{:.2f}".format(PV))

