# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LUVfJ_LYQg2yND1RcQgUD87f80UXXfQd
"""

try:
  
  buyAmountRs = int(input("How many Rupees you want in exchange of USD "))
  buyAmountUsd = buyAmountRs / 69.65
  profit = 50 
  currentUSDprice  = 69.65





  newUSDprice = (profit /round(buyAmountUsd,4) ) + currentUSDprice


except Exception as error:
  print("An exception was thrown!")
  print(str(error))


print("Amount is Rs                      :" ,"Rs{:,}".format(buyAmountRs))
print("Enxchange Rate                    :" ,"{:.4f}".format(newUSDprice))
print("Profit in $                       :" ,"${}".format(profit))
print("Amount to be paid by customer ($) :" ,"${:,.2f}".format(buyAmountUsd))

#{:,}

